<?php

$ano_atual=2024;
$ano_nascimento=2000;

$idade=$ano_atual-$ano_nascimento;

echo"***********************************<br>";
echo"           CÁLCULODE IDADE         <br>";
echo"***********************************<br>";

echo "Ano Atual: $ano_atual <br>";
echo "Ano de Nascimento: $ano_nascimento <br>";
echo "Idade: $idade anos <br>";

echo"***********************************<br>";

?>