<?php

$nota1=8.5;
$nota2=7.0;
$nota3=9.0;
$nota4=6.5;

$media=($nota1+$nota2+$nota3+$nota4)/4;

echo"**************************************<br>";
echo"        MÉDIA DE NOTAS ESCOLARES      <br>";
echo"**************************************<br>";

echo"Nota 1:
 $nota1<br>";
echo"Nota 2: $nota2<br>";
echo"Nota 3: $nota3<br>";
echo"Nota 4: $nota4<br>";
echo"Média: $nota1<br>";

echo"**************************************<br>";

?>