<?php

$idade=20;

if($idade>=18){
    $resultado="Maior de Idade";
} else {
    $resultado="Menor de Idade";
}

echo"**************************************<br>";
echo"          VERIFICAÇÃO DE IDADE        <br>";
echo"**************************************<br>";

echo"Idade: $idade anos <br>";
echo"Resultado: $resultado<br>";

echo"**************************************<br>";

?>